# https://dev.classmethod.jp/articles/assumerole-in-codebuild/

version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16
    commands:
      - aws --version
      
      - echo "[profile deployAccount]" > .awscli-config
      - echo "role_arn = ${DeployRoleArn}" >> .awscli-config
      - echo "credential_source = EcsContainer" >> .awscli-config
      - export AWS_CONFIG_FILE=${CODEBUILD_SRC_DIR}/.awscli-config


      - echo "[deployAccount]" > .awscli-credentials
      - echo "role_arn = ${DeployRoleArn}" >> .awscli-credentials
      - echo "credential_source = EcsContainer" >> .awscli-credentials
      - export AWS_SHARED_CREDENTIALS_FILE=${CODEBUILD_SRC_DIR}/.awscli-credentials


      - npm install

  build:
    commands:
      - cat .awscli-config
      - cat ${CODEBUILD_SRC_DIR}/.awscli-config

      - cat .awscli-credentials
      - cat ${CODEBUILD_SRC_DIR}/.awscli-credentials


      - aws sts get-caller-identity
      - aws sts get-caller-identity --profile deployAccount

      - export AWS_SDK_LOAD_CONFIG=1
      - npx sls deploy --aws-profile deployAccount --verbose