# https://dev.classmethod.jp/articles/assumerole-in-codebuild/

version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16
    commands:
      - echo "[profile deploy-account]" > .awscli-config
      - echo "role_arn = ${DeployRoleArn}" >> .awscli-config
      - echo "credential_source = EcsContainer" >> .awscli-config
      - export AWS_CONFIG_FILE=${CODEBUILD_SRC_DIR}/.awscli-config

      # - npm install

  build:
    commands:
      - cat .awscli-config
      - cat ${CODEBUILD_SRC_DIR}/.awscli-config
      - aws sts get-caller-identity
      - aws sts get-caller-identity --profile deploy-account

      # - npx sls deploy