# https://dev.classmethod.jp/articles/created-codepipeline-with-cloudformation/#toc-5
AWSTemplateFormatVersion: "2010-09-09"

Description: CodeBuild Stack

Parameters:
# ------------------------------------------------------------#
# Parameters
# ------------------------------------------------------------# 
  Name:
    MaxLength: 255
    Type: String
    Default: serverless-codepipeline-code-build

Resources:
# ------------------------------------------------------------#
# CodeBuild
# ------------------------------------------------------------# 
  CodeBuild:
    Type: AWS::CodeBuild::Project
    Properties: 
      Artifacts:
        Type: CODEPIPELINE
      Environment:
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/amazonlinux2-x86_64-standard:4.0
        Type: LINUX_CONTAINER
      Name: !Ref Name
      ServiceRole: !ImportValue iam-role-codebuild-arn
      Source: 
        BuildSpec: buildspec.yml
        Type: CODEPIPELINE
      Tags:
        - Key: Name
          Value: !Ref Name

Outputs:
# ------------------------------------------------------------#
# Outputs
# ------------------------------------------------------------# 
  CodeBuildProjectname:
    Value: !Ref CodeBuild
    Export: 
      Name: codebuild-project-name

  CodeBuildProjectARN:
    Value: !GetAtt CodeBuild.Arn
    Export: 
      Name: codebuild-project-arn
